language: node_js
node_js:
  - "5.5.0"
before_install:
  - npm install -g istanbul codeclimate-test-reporter
install:
  - npm install
before_script:
  - istanbul cover node_modules/mocha/bin/_mocha -- -R spec
  - CODECLIMATE_REPO_TOKEN=274c88b0357b953819d602c2c00c48de8d9e31d8187807ace8c4f68dca28106b codeclimate-test-reporter < coverage/lcov.info