language: node_js
node_js:
  - "5.5.0"
before_install:
  - npm install -g istanbul codeclimate-test-reporter
install:
  - npm install
before_script:
  - istanbul cover node_modules/mocha/bin/_mocha -- -R spec
  - CODECLIMATE_REPO_TOKEN=d210f49e5d8d4c330135b745b0b0047eaa83237e77884a5cbcf2b01467a5a5f4 codeclimate-test-reporter < coverage/lcov.info